# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pull_request_number', models.IntegerField(blank=True, null=True, verbose_name='Pull request number')),
                ('pull_request_url', models.URLField(blank=True, verbose_name='Pull request URL')),
                ('author', models.CharField(max_length=200, verbose_name='Addon author')),
                ('author_email', models.EmailField(max_length=254, verbose_name="Author's email")),
                ('addon_source_url', models.URLField(verbose_name='Addon source')),
                ('addon_description', models.TextField(verbose_name='Addon description')),
                ('addon_id', models.CharField(db_index=True, max_length=200, verbose_name='Addon ID')),
                ('addon_version', models.CharField(db_index=True, max_length=50, verbose_name='Addon version')),
                ('git_repo', models.CharField(choices=[('repo-scripts', 'Script addons'), ('repo-plugins', 'Content plugins')], default='repo-scripts', max_length=50, verbose_name='Git repository')),
                ('git_branch', models.CharField(choices=[('leia', '18 Leia'), ('krypton', '17 Krypton'), ('jarvis', '16 Jarvis'), ('isengard', '15 Isengard')], default='leia', max_length=50, verbose_name='Git branch')),
                ('zipped_addon', models.FileField(upload_to='', verbose_name='Zipped addon')),
                ('send_notifications', models.BooleanField(default=True, verbose_name='Send notifications')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Pull Request',
                'verbose_name_plural': 'Pull Requests',
                'ordering': ('-pk',),
            },
        ),
    ]
